firstly, import all the important libraries

In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

create your three sentences

In [2]:
sentences = [
    "In a solitary style and crash the cemetery gates",
    "I have been waiting for this",
    "The weather is terrible"
]

create a tokenizer

In [3]:
tokenizer = Tokenizer()

fit the tokenizer

In [4]:
tokenizer.fit_on_texts(sentences)

see the vocabulary

In [5]:
print(tokenizer.word_index)

{'the': 1, 'in': 2, 'a': 3, 'solitary': 4, 'style': 5, 'and': 6, 'crash': 7, 'cemetery': 8, 'gates': 9, 'i': 10, 'have': 11, 'been': 12, 'waiting': 13, 'for': 14, 'this': 15, 'weather': 16, 'is': 17, 'terrible': 18}


convert sentences into vectors

In [6]:
sequences = tokenizer.texts_to_sequences(sentences)

print(sequences)

[[2, 3, 4, 5, 6, 7, 1, 8, 9], [10, 11, 12, 13, 14, 15], [1, 16, 17, 18]]


pad the sequences

In [7]:
padded_sequences = pad_sequences(sequences, padding='post')

print(padded_sequences)

[[ 2  3  4  5  6  7  1  8  9]
 [10 11 12 13 14 15  0  0  0]
 [ 1 16 17 18  0  0  0  0  0]]


create embedding layer

In [8]:
embedding_layer = tf.keras.layers.Embedding(
    input_dim=len(tokenizer.word_index)+1,
    output_dim=8
)

convert vectors into embeddings

In [9]:
embeddings = embedding_layer(padded_sequences)

print(embeddings)

tf.Tensor(
[[[-3.2817617e-02  3.6151338e-02 -9.2022531e-03 -6.2064528e-03
   -2.0599162e-02 -3.5504330e-02 -4.6248626e-02  3.2475445e-02]
  [-4.4549119e-02 -4.9907614e-02  4.4578109e-02 -4.4092562e-02
    1.3776962e-02 -1.1879563e-02  4.7056865e-02  4.5319308e-02]
  [ 3.2357227e-02  2.7125131e-02  3.3968989e-02  1.9231688e-02
    2.8885666e-02 -9.1102235e-03 -4.7144517e-03 -2.9209746e-02]
  [ 4.5463119e-02  3.8117599e-02  2.9410589e-02 -7.2743893e-03
   -2.5727725e-02  4.8954438e-02 -1.9451594e-02 -3.7632920e-02]
  [-4.4798639e-02  3.2891408e-03  4.5711506e-02  3.9250467e-02
    1.6218830e-02 -1.9093668e-02 -4.2017244e-02  1.7272200e-02]
  [ 4.5083463e-05  4.9101003e-03 -4.7932770e-02 -2.2003639e-02
    1.1677466e-02 -5.2967072e-03 -3.3258870e-02  4.1716013e-02]
  [-2.9398669e-02 -9.4377398e-03 -3.4398757e-02  3.6876131e-02
   -3.1162430e-02  9.7793341e-03 -4.3949962e-02 -1.2752473e-02]
  [ 3.6548223e-02  2.6728977e-02 -1.8130399e-02 -9.1731548e-04
    1.3900053e-02 -3.3621181e-02 -3.5

assign sentiment labels

In [10]:
labels = np.array([1,1,0])

build a sentiment model

In [11]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(
        input_dim=len(tokenizer.word_index)+1,
        output_dim=8
    ),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

compile the model

In [12]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

train the model

In [13]:
model.fit(
    padded_sequences,
    labels,
    epochs=30
)

Epoch 1/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 824ms/step - accuracy: 0.3333 - loss: 0.6918
Epoch 2/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.6905
Epoch 3/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 1.0000 - loss: 0.6895
Epoch 4/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.6884
Epoch 5/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 1.0000 - loss: 0.6874
Epoch 6/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 1.0000 - loss: 0.6863
Epoch 7/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.6852
Epoch 8/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 1.0000 - loss: 0.6842
Epoch 9/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.6831
Epoch 10/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.6821
Epoch 11/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.6808
Epoch 12/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 1.0000 - loss: 0.6796


predict sentiment/ predict a new sentence

In [14]:
new_sentence = [
    "the awful things that i have seen"
]

new_sequence = tokenizer.texts_to_sequences(new_sentence)

new_padded = pad_sequences(
    new_sequence,
    maxlen=padded_sequences.shape[1],
    padding='post'
)

prediction = model.predict(new_padded)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step


In [15]:
if prediction[0][0] > 0.5:
    print("Positive")
else:
    print("Negative")

Positive
